services:
  checkmk:
    image: "checkmk/check-mk-raw:2.4.0-latest"
    container_name: "checkmk"
    environment:
      - CMK_PASSWORD=4Iz2QqGj327ibh
      - TZ=America/New_York
    volumes:
      - ./monitoring:/omd/sites
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    # ports:
      # - 8081:5000
      # - 8010:8000
    restart: always
    networks:
      - custom-bridge

networks:
  custom-bridge:
    external: true
