version: "3.8"

services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    ports:
      - 8085:3000
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: 
      SEMAPHORE_ADMIN_PASSWORD:
      SEMAPHORE_ADMIN_NAME:
      SEMAPHORE_ADMIN_EMAIL: 
    volumes:
      - /semaphore/data:/var/lib/semaphore
      - /semaphore/semaphore_config:/etc/semaphore
      - /semaphore/semaphore_tmp:/tmp/semaphore
    networks:
      - custom-bridge

networks:
  custom-bridge:
    external: true
